# Artificial Neural Network

### Importing the libraries

In [190]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [192]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

### Categorical Data Encoding

Label Encoding the "Gender" column

In [195]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
#X[:, 2] = le.inverse_transform(X[:, 2].astype(int))

In [196]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [259]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [198]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [199]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)


### Feature Scaling

In [200]:
a=X_test
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [201]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [202]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [203]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [204]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [205]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [206]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 559us/step - loss: 0.8515 - accuracy: 0.5089
Epoch 2/100
250/250 [==============================] - 0s 593us/step - loss: 0.4894 - accuracy: 0.7989
Epoch 3/100
250/250 [==============================] - 0s 544us/step - loss: 0.4465 - accuracy: 0.8087
Epoch 4/100
250/250 [==============================] - 0s 547us/step - loss: 0.4313 - accuracy: 0.8139
Epoch 5/100
250/250 [==============================] - 0s 555us/step - loss: 0.4238 - accuracy: 0.8188
Epoch 6/100
250/250 [==============================] - 0s 544us/step - loss: 0.4189 - accuracy: 0.8231
Epoch 7/100
250/250 [==============================] - 0s 556us/step - loss: 0.4150 - accuracy: 0.8257
Epoch 8/100
250/250 [==============================] - 0s 547us/step - loss: 0.4116 - accuracy: 0.8279
Epoch 9/100
250/250 [==============================] - 0s 584us/step - loss: 0.4087 - accuracy: 0.8331
Epoch 10/100
250/250 [==============================] - 0s 537us/step - l

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Testing on one customer**

In [207]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


### Predicting the Test set results

In [231]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [265]:
for i in range(len(X_test)):
  print("%s %s" % (a[i], y_pred[i]))
  #df12 = np.concatenate(a[i],y_pred[i])
#print(X_test[1],a[1])

[0.0 1.0 0.0 597 'Female' 35 8 131101.04 1 1 1 192852.67] [False]
[1.0 0.0 0.0 523 'Female' 40 2 102967.41 1 1 0 128702.1] [False]
[0.0 0.0 1.0 706 'Female' 42 8 95386.82 1 1 1 75732.25] [False]
[1.0 0.0 0.0 788 'Male' 32 4 112079.58 1 0 0 89368.59] [False]
[0.0 1.0 0.0 706 'Male' 38 5 163034.82 2 1 1 135662.17] [False]
[0.0 0.0 1.0 670 'Female' 57 3 175575.95 2 1 0 99061.75] [ True]
[0.0 0.0 1.0 590 'Male' 34 0 65812.35 2 0 1 160346.3] [False]
[0.0 0.0 1.0 636 'Female' 29 6 157576.47 2 1 1 101102.39] [False]
[1.0 0.0 0.0 598 'Female' 64 9 0.0 1 0 1 13181.37] [False]
[1.0 0.0 0.0 456 'Female' 63 1 165350.61 2 0 0 140758.07] [ True]
[1.0 0.0 0.0 498 'Female' 31 10 0.0 2 1 0 13892.57] [False]
[0.0 0.0 1.0 714 'Male' 45 8 150900.29 2 0 1 139889.15] [False]
[0.0 1.0 0.0 488 'Female' 33 4 140002.35 1 1 0 123613.81] [False]
[0.0 1.0 0.0 562 'Female' 31 9 117153.0 1 1 1 108675.01] [False]
[0.0 1.0 0.0 772 'Female' 51 9 143930.92 1 0 1 46675.51] [ True]
[0.0 1.0 0.0 667 'Male' 55 9 154393.43 1

In [256]:
df1 = pd.DataFrame(data = y_pred,columns={'Prediction'})

RowNumber  CustomerId  ... EstimatedSalary  Prediction
0             1    15634602  ...       101348.88       False
1             2    15647311  ...       112542.58       False
2             3    15619304  ...       113931.57       False
3             4    15701354  ...        93826.63       False
4             5    15737888  ...        79084.10       False
...         ...         ...  ...             ...         ...
1995       1996    15617648  ...       106564.88       False
1996       1997    15755678  ...        42763.12       False
1997       1998    15624781  ...       168753.34       False
1998       1999    15779497  ...        19483.35       False
1999       2000    15567399  ...       158646.46       False

[2000 rows x 14 columns]

### Confusion Matrix

In [210]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 195  210]]


0.8585